AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Template for Cloud Resume Challenge

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: "'*'"
        AllowMethods: "'GET, POST, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowCredentials: true

  MyDynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_code/
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Timeout: 300
      Environment:
        Variables:
          tablename: !Ref MyDynamoDBTable
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /path

      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "dynamodb:GetItem"
                - "dynamodb:UpdateItem"
              Resource: !GetAtt
                - MyDynamoDBTable
                - Arn
